export default {
  active: true,
  name: 'Index',
  // path: '/examples/example-c',
  source: 'documents/examples/example-c',
  target: 'localhost/examples/example-c',
  ignore: [],
  main: 'index.html',
  pilers: {
    sans: [{
      name: 'ClearPiler',
      type: 'sans',
      target: 'source',
      path: ['**/template.js'],
      ignore: ['**/$template.js'],
    }, {
      name: 'ClearPiler',
      type: 'sans',
      target: 'target',
      path: ['*.{html,css,js,md,map,ico}'],
      ignore: [],
    }],
    simules: [{
      name: 'SimulePiler',
      type: 'simules',
      outputType: 'path',
      input: 'favicon.ico',
      output: 'favicon.ico',
      watch: ['favicon.ico'],
      ignore: [],
    }, {
      name: 'SimulePiler',
      type: 'simules',
      outputType: 'path',
      input: '../../../../node_modules/recourse/distributement/recourse.js',
      output: '../../../static/dependencies/recourse.js',
      watch: ['../../../../node_modules/recourse/distributement/recourse.js'],
      ignore: [],
    }, {
      name: 'SimulePiler',
      type: 'simules',
      outputType: 'path',
      input: '../../../../node_modules/recourse/distributement/recourse.js.map',
      output: '../../../static/dependencies/recourse.js.map',
      watch: ['../../../../node_modules/recourse/distributement/recourse.js.map'],
      ignore: [],
    }],
    styles: [{
      name: 'SASSPiler',
      type: 'styles',
      input: 'index.scss',
      output: 'index.css',
      watch: ['**/*.scss'],
      ignore: [],
      inputOptions: {},
      outputOptions: {
        sourceMap: true,
      },
    }],
    scripts: [{
      name: 'RollupPiler',
      type: 'scripts',
      watch: ['**/*.js'],
      ignore: [
        '**/$route.js',
        '**/$document.js',
        '**/$socket.js',
      ],
      input: 'index.js',
      output: 'index.js',
      inputOptions: {
        logLevel: 'silent', 
        external: [
          '/dependencies/core-plex.js',
          '/coutil/index.js',
        ],
      },
      outputOptions: {
        format: 'es',
        sourcemap: true,
      },
    }],
    structs: [{
      name: 'EJSPiler',
      type: 'structs',
      outputType: 'server',
      model: 'index.json',
      watch: ['**/*.{ejs,json}'],
      ignore: ['**/$*.ejs'],
      input: 'index.ejs',
      output: 'index.html',
      outputOptions: {
        localsName: '$content',
        root: ['templates'],
      },
    }, {
      name: 'EJSPiler',
      type: 'structs',
      outputType: 'client',
      watch: ['**/$*.ejs'],
      ignore: [],
      input: '**/*.ejs',
      output: '',
      outputOptions: {
        localsName: '$content',
        root: [''],
      }, 
    }],
  }
}